repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      types: [python]
      exclude: ^(scripts|tests)/
      args: [--rcfile=.pylintrc, --fail-under=9]
      additional_dependencies: [pylint, flask, waitress, requests]
